name: build-ifc

on: [push]

jobs:

  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: ifc
        image_tag: alpine-3.18
        dockerfile: alpine.Dockerfile
