name: build-ifc

on: [push]

jobs:
  build-ifc-sdk-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: ifc
        image_tag: alpine-3.18
        dockerfile: alpine.Dockerfile

  create-ifc-file:
    runs-on: windows-latest
    needs: build-ifc-sdk-alpine
    steps:
    - uses: ilammy/msvc-dev-cmd@v1.12.1
    - uses: actions/checkout@v4
    - name: Create IFC file
      shell: pwsh
      run: cl /std:c++20 /exportHeader test.cpp
    - uses: actions/upload-artifact@v3
      with:
        name: ifc-file
        path: test.cpp.ifc

  use-ifc-file:
    runs-on: ubuntu-latest
    needs: create-ifc-file
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ifc-file
    - name: Use IFC file
      run: docker run --rm -v "$PWD"/test.cpp.ifc:/test.cpp.ifc ghcr.io/whoan/ifc-playground/ifc:alpine-3.18 ifc-printer /test.cpp.ifc
